### ISSUE TITLE
Can you make Find Replace In Keywords.jsx? - I tried to edit your code, it works for Title but not for Keywords

### ISSUE THREAD

**Issue by astx123** [Paul-Riggott/PS-Scripts#2]
Find Replace has very useful functionality which I need very much for Keywords instead of Description.

I tried to replace "description" to "keywords" (with and without "Description" > "Keywords") and it didn't work. I don't know anything about javascript so I don't know what else can I try to make it work...

So can you write Find Replace In Keywords.jsx?

**Comment by astx123** [comment]
I tried to change "description" into "title" to make the script work for the Title section and it worked.

So the question is what exactly should replace "keywords"?

I saw in one your script that for Bridge it should be "Key Words" (separate), so if that's the case, how should I write that in the code? (yes, I'm a noob in javascript)

**Comment by astx123** [comment]
ok, I found different script which provides the functionality I need, and even better since it can add and remove keywords.

However, the question what should be but instead of "description" in your code still remains, I'm curious.

**Comment by Paul-Riggott** [comment]
They are totally different type of fields, and the script would have to be re-writen for keywords, there is no easy change.
